name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.12.1

jobs:
  flake8:
    name: "Linter with flake8"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: "Installing poetry"
        run: pip install poetry

      - name: "Installing dependencies"
        run: poetry install

      - name: Linter with flake8
        run: |
          poetry run flake8 .

  black:
    name: "Linter with black"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: "Installing black"
        run: pip install poetry

      - name: "Installing dependencies"
        run: poetry install

      - name: Linter with black
        run: |
          poetry run black --check .

  isort:
    name: "Linter with isort"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: "Installing isort"
        run: pip install poetry

      - name: "Installing dependencies"
        run: poetry install

      - name: Linter with isort
        run: |
          poetry run isort --check .

  ruff:
    name: "Linter with ruff"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: "Installing poetry"
        run: pip install poetry

      - name: "Installing dependencies"
        run: poetry install

      - name: Linter with ruff
        run: |
          poetry run ruff check .

  mypy:
    name: "Linter with mypy"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: "Installing mypy"
        run: pip install poetry

      - name: "Installing dependencies"
        run: poetry install

      - name: Linter with mypy
        run: |
          poetry run mypy .

  test:
    name: "Testing code"
    runs-on: ubuntu-latest
    needs: [flake8, black, isort, ruff, mypy]
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: "Installing poetry"
        run: pip install poetry

      - name: "Installing dependencies"
        run: poetry install

      - name: "Testing code"
        run: |
          poetry run coverage run -m pytest
          poetry run coverage html --show-contexts --title="GeoIP"
          poetry run coverage xml

      - name: "Upload report"
        uses: actions/upload-artifact@v3
        with:
          name: coverage.zip
          path: |
            htmlcov/
          retention-days: 30

      - name: "Report coverage"
        run: |
          poetry run coverage report --fail-under=100
